"""Export to a Conversational Analytics API ``DataAgent`` body.

Confirmed against the v1 REST reference (projects.locations.dataAgents), 2026-09-27:
  DataAgent{displayName, description, labels, dataAnalyticsAgent{stagingContext, publishedContext}}
  Context{systemInstruction, datasourceReferences, glossaryTerms[], lookerGoldenQueries[], ...}
  DatasourceReferences{looker{exploreReferences[{lookerInstanceUri, lookmlModel, explore}]}}
  GlossaryTerm{displayName, description, labels[]}
  LookerGoldenQuery{naturalLanguageQuestions[], lookerQuery{model, explore, fields[], filters[{field, value}], sorts[], limit}}

TODO(verify-api):
  * whether ``GlossaryTerm.labels`` is meant for synonyms (we put synonyms there);
  * whether a create request should populate ``stagingContext`` (used here) or ``publishedContext``;
  * recommended structure and size limits of ``systemInstruction`` (we emit sectioned Markdown);
  * GCP label key/value constraints for ``labels`` (we emit lowercase, <=63 chars);
  * the documented cap of five explores per agent (we warn, don't truncate).
"""

from __future__ import annotations

import re
from typing import Any

from lookml_agentops._util.hashing import canonical_json
from lookml_agentops.compile.schema import AgentInstructions

LOOKER_INSTANCE_URI_PLACEHOLDER = "${LOOKER_INSTANCE_URI}"
MAX_EXPLORES = 5


def _label(v: str) -> str:
    return re.sub(r"[^a-z0-9_-]", "-", v.lower())[:63]


def render_system_instruction(instr: AgentInstructions) -> str:
    lines = [
        f"# Agent instructions: {instr.agent_id}",
        f"Generated by lkagent from LookML and the business glossary ({instr.schema_version}, "
        f"content hash {instr.content_hash[:12]}). Edits are overwritten on the next compile.",
        "",
        "Rules are listed hub layer first, then spoke layer. Each rule ID is stable.",
    ]
    for layer in instr.layers:
        lines += ["", f"## Layer {layer.layer_id}"]
        kinds = sorted({r.kind for r in layer.rules})
        for kind in kinds:
            lines += ["", f"### {kind}"]
            lines += [f"- [{r.rule_id}] {r.text}" for r in layer.rules if r.kind == kind]
    return "\n".join(lines) + "\n"


def _map_explore(instr: AgentInstructions, name: str) -> str | None:
    for e in instr.explores:
        if e.explore == name or name in e.extends_chain:
            return e.explore
    return None


def export_ca(instr: AgentInstructions) -> tuple[str, list[str]]:
    """Return (JSON body, warnings)."""
    warnings: list[str] = []
    if len(instr.explores) > MAX_EXPLORES:
        warnings.append(
            f"{instr.agent_id}: {len(instr.explores)} explores exceed the documented maximum of "
            f"{MAX_EXPLORES} per data agent"
        )
    glossary = [g for layer in instr.layers for g in layer.glossary]
    golden: list[dict[str, Any]] = []
    for layer in instr.layers:
        for q in layer.example_questions:
            explore = _map_explore(instr, q.explore)
            if explore is None:
                continue
            query: dict[str, Any] = {
                "model": instr.lookml_model,
                "explore": explore,
                "fields": q.fields,
            }
            if q.filters:
                query["filters"] = [{"field": k, "value": v} for k, v in sorted(q.filters.items())]
            golden.append({"naturalLanguageQuestions": [q.question], "lookerQuery": query})
    context: dict[str, Any] = {
        "systemInstruction": render_system_instruction(instr),
        "datasourceReferences": {
            "looker": {
                "exploreReferences": [
                    {
                        "lookerInstanceUri": LOOKER_INSTANCE_URI_PLACEHOLDER,
                        "lookmlModel": instr.lookml_model,
                        "explore": e.explore,
                    }
                    for e in instr.explores
                ]
            }
        },
        "glossaryTerms": [
            {"displayName": g.name, "description": g.definition, "labels": g.synonyms}
            for g in glossary
        ],
        "lookerGoldenQueries": golden,
    }
    body = {
        "displayName": f"{instr.agent_id} ({instr.lookml_model})",
        "description": f"lkagent-compiled data agent for {instr.agent_id}.",
        "labels": {
            "managed-by": "lkagent",
            "lkagent-agent": _label(instr.agent_id),
            "lkagent-hash": instr.content_hash[:16],
        },
        "dataAnalyticsAgent": {"stagingContext": context},
    }
    return canonical_json(body), warnings
