"""Text for the Looker UI agent editor.

The UI editor has: Agent name, Agent description, Explores (up to five), Instructions (free text;
YAML or Markdown recommended) and Verified queries (a question plus an Explore URL). Its context
types differ from the API's; see the "Does not translate" section this exporter writes.
"""

from __future__ import annotations

from lookml_agentops.spec.model import AgentSpec


def export_looker_ui(spec: AgentSpec) -> str:
    lines = [
        f"# Looker UI setup: {spec.agent_id}",
        "",
        "<!-- generated by lkagent generate compile; edits are overwritten -->",
        "",
        "## Agent name",
        spec.agent_id,
        "",
        "## Agent description",
        spec.description,
        "",
        "## Explores",
        *[f"- {e.model or e.project} / {e.explore}" for e in spec.explores],
        "",
        "## Instructions (paste into the Instructions field)",
        "",
        "```markdown",
    ]
    if spec.role:
        lines += ["# Persona", spec.role.text]
    if spec.audience:
        lines += ["", "# Audience", spec.audience.text]
    rules = spec.active_rules()
    if rules:
        lines += ["", "# Rules", *[f"- {r.text}" for r in rules]]
    terms = [(v.phrases, v.field or v.target) for v in spec.vocabulary]
    if spec.derived:
        terms += [([t.term.lower(), *t.synonyms], t.field or "") for t in spec.derived.glossary]
    if terms:
        lines += ["", "# Terms"]
        lines += [
            f"- {', '.join(repr(p) for p in phrases)}: use {target}" for phrases, target in terms
        ]
    if spec.guardrails:
        lines += ["", "# Guardrails", *[f"- {g.text}" for g in spec.guardrails]]
    lines += ["```", "", "## Verified queries"]
    untranslated: list[str] = []
    for q in spec.golden_queries:
        if q.explore_url:
            lines.append(f"- Question: {q.questions[0]}  \n  Answer (Explore URL): {q.explore_url}")
        else:
            lines.append(
                f"- Question: {q.questions[0]}  \n  Answer: *needs an Explore URL* (defined inline as a "
                "looker_query; open it in an Explore, share, and paste the URL)"
            )
            untranslated.append(
                f"golden query `{q.golden_id}` is inline; the UI only accepts Explore URLs"
            )
        if len(q.questions) > 1:
            untranslated.append(
                f"golden query `{q.golden_id}` has {len(q.questions)} phrasings; the UI takes one "
                "question per verified query (add the others as separate entries)"
            )
    lines += ["", "## Does not translate", ""]
    untranslated += [
        "structured glossary entries: the UI has no glossary field, so terms are written into Instructions",
        "rule ids and `locked` flags: the UI stores plain text, so lock enforcement happens only in lkagent",
        "provenance (file:line) for rules and golden queries",
    ]
    if spec.derived and spec.derived.descriptions:
        untranslated.append(
            "derived LookML descriptions: the UI reads them from LookML directly; not repeated"
        )
    lines += [f"- {u}" for u in untranslated]
    return "\n".join(lines) + "\n"
