"""Render docs/lint-rules.md from the rule registry (kept in sync by a test)."""

from __future__ import annotations

from lookml_agentops.lint.rules import ALL_RULES


def render_rules_markdown() -> str:
    out = [
        "# Lint rules",
        "",
        "<!-- generated by `python -m lookml_agentops.lint.docs`; do not edit by hand -->",
        "",
        "Configure rules in `lkagent.yaml`:",
        "",
        "```yaml",
        "lint:",
        "  max_ai_fields: 150",
        "  rules:",
        "    LKA009: {severity: warning}",
        "    LKA012: {enabled: false}",
        "```",
        "",
        'Exempt a single object with `# lkagent:disable LKA001 reason="..."` on the line above it.',
        "",
        "| ID | Name | Default | Rationale | Fix |",
        "|---|---|---|---|---|",
    ]
    for r in ALL_RULES:
        out.append(f"| {r.id} | `{r.name}` | {r.severity} | {r.rationale} | {r.fix_hint} |")
    return "\n".join(out) + "\n"


if __name__ == "__main__":  # pragma: no cover
    print(render_rules_markdown(), end="")
